language: node_js
node_js:
  - "7"
  - "8"
  - "9"
services:
  - mysql
  - mongodb
  - redis
after_success: 
  - nyc report --reporter=text-lcov | coveralls
deploy:
  provider: npm
  email: yr0319@126.com
  api_key: 438c9fe0-e2d6-4e7e-8559-ad7c8eed53a2
  on:
    branch: master
